# Generated by Django 4.2.1 on 2023-06-05 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Alias', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('received', models.BooleanField(default=False)),
                ('submitted', models.BooleanField(default=False)),
                ('tracking_id', models.CharField(blank=True, max_length=255, null=True)),
                ('courier', models.CharField(blank=True, max_length=255, null=True)),
                ('total_cost', models.FloatField()),
                ('publish', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PUrchaseOrderSUbmit',
            fields=[
                ('PurchaseOrderID', models.AutoField(primary_key=True, serialize=False)),
                ('perchase_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_submit', to='warehouse.purchaseorder')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='Supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='warehouse.supplier'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='products',
            field=models.ManyToManyField(to='Order.products'),
        ),
    ]
