# Generated by Django 4.2.1 on 2023-05-31 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Order', '0016_alter_products_orderline_alter_products_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('PurchaseOrderID', models.AutoField(primary_key=True, serialize=False)),
                ('Alias', models.CharField(blank=True, max_length=255, null=True)),
                ('Supplier', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('quantities_ordered', models.IntegerField()),
                ('received', models.BooleanField(default=False)),
                ('submitted', models.BooleanField(default=False)),
                ('tracking_id', models.CharField(blank=True, max_length=255, null=True)),
                ('courier', models.CharField(blank=True, max_length=255, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantities_received', models.IntegerField()),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='Order.products')),
            ],
        ),
    ]
