# Generated by Django 4.2.1 on 2023-05-29 13:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_Order',
            fields=[
                ('Purchase_Order_ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Created_Date', models.DateTimeField()),
                ('Supplier', models.CharField(max_length=255)),
                ('Cost', models.FloatField()),
                ('Tracking_ID', models.CharField(max_length=255)),
                ('Courier_Company_Name', models.CharField(max_length=255)),
                ('Order_Line_ID', models.CharField(max_length=255)),
                ('SKU', models.CharField(max_length=255)),
                ('Par_No', models.CharField(max_length=255)),
                ('Quantity', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Purchase Order',
            },
        ),
        migrations.CreateModel(
            name='Stock_Data',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock', models.IntegerField()),
                ('Product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Order.products')),
            ],
            options={
                'verbose_name_plural': 'Stock Data',
            },
        ),
    ]
