# Generated by Django 4.2.1 on 2023-05-29 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_products_supplier'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_order',
            name='SKU',
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='Order_Line_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Order.orderline'),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='Supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Order.supplier'),
        ),
    ]
