# Generated by Django 4.2.1 on 2023-06-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='order_date',
            field=models.DateTimeField(),
        ),
    ]
