# Generated by Django 4.2.1 on 2023-05-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_remove_purchaseorder_products_purchaseorder_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='quantities_ordered',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_cost',
            field=models.FloatField(),
        ),
    ]
