# Generated by Django 4.2.1 on 2023-06-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_supplier_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
