# Generated by Django 4.2.1 on 2023-05-31 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_remove_purchaseorder_quantities_ordered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='quantities_received',
        ),
    ]
