# Generated by Django 4.2.1 on 2023-06-01 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_remove_purchaseorder_quantities_received'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='total_cost',
        ),
    ]
