# Generated by Django 4.2.1 on 2023-06-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_alter_purchaseorder_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
