# Generated by Django 4.2.1 on 2023-06-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_purchaseorder_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='Supplier',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_id',
            field=models.CharField(max_length=255),
        ),
    ]
