# Generated by Django 4.2.1 on 2023-06-05 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0021_remove_products_quantities_received_and_more'),
        ('warehouse', '0009_alter_purchaseorder_supplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='order_id',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='Order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Order.order'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='Supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.supplier'),
        ),
    ]
