# Generated by Django 4.2.1 on 2023-06-05 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0021_remove_products_quantities_received_and_more'),
        ('warehouse', '0010_supplier_remove_purchaseorder_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='Order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.order'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='Supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.supplier'),
        ),
    ]
