# Generated by Django 4.2.1 on 2023-06-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_alter_purchaseorder_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='Supplier',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
