# Generated by Django 4.2.1 on 2023-06-07 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0013_alter_purchaseorder_purchaseorderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='Order',
        ),
    ]
