# Generated by Django 4.2.1 on 2023-06-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0014_remove_purchaseorder_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
