# Generated by Django 4.2.1 on 2023-06-05 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ShippingOption', models.CharField(max_length=100)),
                ('DatePlaced', models.DateTimeField()),
                ('OrderStatus', models.CharField(max_length=100)),
                ('SalesChannel', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Orders',
                'ordering': ('-DatePlaced',),
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('OrderLineID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField()),
                ('SKU', models.CharField(max_length=100)),
                ('eBay', models.CharField(blank=True, max_length=100, null=True)),
                ('quantities_received', models.IntegerField(default=0)),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='Order.order')),
            ],
            options={
                'verbose_name_plural': 'Order Lines',
                'ordering': ('-OrderLineID',),
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('OrderLine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='products', serialize=False, to='Order.orderline')),
                ('sku', models.CharField(max_length=100)),
                ('misc27', models.CharField(max_length=10)),
                ('inventory_id', models.CharField(max_length=10)),
                ('default_price', models.FloatField()),
                ('ack', models.CharField(blank=True, max_length=10, null=True)),
                ('po_generated', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Order.order')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ('-sku',),
            },
        ),
    ]
