# Generated by Django 4.2.1 on 2023-05-29 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('ShippingOption', models.CharField(max_length=255)),
                ('CustomerRef4', models.CharField(blank=True, max_length=255)),
                ('SalesChannel', models.CharField(max_length=255)),
                ('InternalOrderNotes', models.TextField(blank=True)),
                ('OrderID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('CustomerRef6', models.CharField(blank=True, max_length=255)),
                ('CustomerRef3', models.CharField(blank=True, max_length=255)),
                ('DatePlaced', models.DateTimeField()),
                ('OrderStatus', models.CharField(max_length=255)),
                ('CustomerRef5', models.TextField(blank=True)),
                ('CustomerRef7', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('SKU', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Product_Name', models.CharField(max_length=255)),
                ('Product_Description', models.CharField(max_length=255)),
                ('Product_Price', models.FloatField()),
                ('product_Qty', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('Supplier_ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Supplier_Name', models.CharField(max_length=255)),
                ('Supplier_Address', models.CharField(max_length=255)),
                ('Supplier_Phone', models.CharField(max_length=255)),
                ('Supplier_Email', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Supplier',
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('eBay', models.CharField(blank=True, max_length=255)),
                ('Quantity', models.IntegerField()),
                ('SKU', models.CharField(max_length=255)),
                ('OrderLineID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ItemNotes', models.TextField(blank=True)),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='Order.order')),
            ],
            options={
                'verbose_name_plural': 'Order Lines',
            },
        ),
    ]
