# Generated by Django 4.2.1 on 2023-05-30 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_Data',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='OrderLine_Data',
            new_name='OrderLine',
        ),
    ]
