# Generated by Django 4.2.1 on 2023-05-30 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_rename_order_data_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_placed',
            new_name='DatePlaced',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='OrderID',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_status',
            new_name='OrderStatus',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='sales_channel',
            new_name='SalesChannel',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_option',
            new_name='ShippingOption',
        ),
        migrations.RenameField(
            model_name='orderline',
            old_name='order',
            new_name='Order',
        ),
        migrations.RenameField(
            model_name='orderline',
            old_name='order_line_id',
            new_name='OrderLineID',
        ),
        migrations.RenameField(
            model_name='orderline',
            old_name='quantity',
            new_name='Quantity',
        ),
        migrations.RenameField(
            model_name='orderline',
            old_name='sku',
            new_name='SKU',
        ),
    ]
