# Generated by Django 4.2.1 on 2023-06-05 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_supplier_order_date'),
        ('Order', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='warehouse.supplier'),
        ),
    ]
