# Generated by Django 4.2.1 on 2023-05-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_rename_date_placed_order_dateplaced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='eBay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
