# Generated by Django 4.2.1 on 2023-05-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='default_price',
            field=models.FloatField(),
        ),
    ]
