# Generated by Django 4.2.1 on 2023-05-30 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_alter_products_default_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Order.order'),
        ),
    ]
