# Generated by Django 4.2.1 on 2023-05-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0008_alter_products_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-DatePlaced',), 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderline',
            options={'ordering': ('-OrderLineID',), 'verbose_name_plural': 'Order Lines'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('-sku',), 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='products',
            name='ack',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='current_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
