# Generated by Django 4.2.1 on 2023-05-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0009_alter_order_options_alter_orderline_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ack',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='current_time',
            field=models.DateTimeField(),
        ),
    ]
