# Generated by Django 4.2.1 on 2023-05-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0010_alter_products_ack_alter_products_current_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='current_time',
        ),
        migrations.AlterField(
            model_name='products',
            name='ack',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
