# Generated by Django 4.2.1 on 2023-05-30 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0011_remove_products_current_time_alter_products_ack'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('DatePlaced',), 'verbose_name_plural': 'Orders'},
        ),
    ]
