# Generated by Django 4.2.1 on 2023-05-30 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0012_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-DatePlaced',), 'verbose_name_plural': 'Orders'},
        ),
    ]
