# Generated by Django 4.2.1 on 2023-05-31 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0013_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='OrderLine',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Order.orderline'),
        ),
    ]
