# Generated by Django 4.2.1 on 2023-05-31 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0014_products_orderline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='OrderLine',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Order.orderline'),
        ),
    ]
