# Generated by Django 4.2.1 on 2023-05-31 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0015_alter_products_orderline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='OrderLine',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='products', serialize=False, to='Order.orderline'),
        ),
        migrations.AlterField(
            model_name='products',
            name='sku',
            field=models.CharField(max_length=100),
        ),
    ]
