# Generated by Django 4.2.1 on 2023-06-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0019_alter_products_quantities_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='quantities_received',
            field=models.IntegerField(default=0),
        ),
    ]
