# Generated by Django 4.2.1 on 2023-06-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0020_alter_products_quantities_received'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='quantities_received',
        ),
        migrations.AddField(
            model_name='orderline',
            name='quantities_received',
            field=models.IntegerField(default=0),
        ),
    ]
