name: CI/CD

on:
  push:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        python manage.py test

  merge_to_main:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Merge to main
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git fetch
        git merge --ff-only ${{ github.sha }}
        git remote set-url origin https://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@github.com/ashwani-bluethink/SOW.git
        git push origin main
